# Generated by Django 5.1.6 on 2025-02-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('lecture', 'Lectures'), ('plumes', 'Plume'), ('meditations', 'Méditations'), ('Anime_musique_series', 'Animé musique & séries ')], max_length=20)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_publication', models.DateField(auto_now=True)),
                ('lien_video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
