# Generated by Django 5.1.6 on 2025-02-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('lecture', 'Lectures'), ('plume', 'Plume'), ('meditations', 'Méditations'), ('Anime_musique_series', 'Animé musique & séries ')], max_length=20),
        ),
    ]
