# Generated by Django 5.1.6 on 2025-02-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('livres', 'Livres'), ('plume', 'Plume'), ('meditations', 'Méditations'), ('Anime_musique_series', 'Animé musique & séries ')], max_length=20),
        ),
    ]
